cadastros/urls.py
from django.urls import path
from . import views

app_name = 'cadastros'

urlpatterns = [
    # perfis
    path('profiles_list/',views.perfis_list_view, name='profiles_list'),
    path('profile_delete/<int:pk>/', views.perfis_delete_view, name='profile_delete'),
    # chamadas
    path('chamadas_list/',views.chamadas_list_view, name='chamadas_list'),
    path('chamada_create/', views.chamadas_create_view, name='chamada_create'),
    path('chamada_delete/<int:pk>/', views.chamada_delete_view, name='chamada_delete'),
    path('chamada_update/<int:pk>/', views.chamada_update_view, name='chamada_update'),
    # noticias
    path('noticias_list/', views.noticia_list_view, name='noticias_list'),
    path('noticias_create/', views.noticia_create_view, name='noticias_create'),
    path('noticias_update/<int:pk>/', views.noticia_update_view, name='noticias_update'),
    path('noticias_delete/<int:pk>/', views.noticia_delete_view, name='noticias_delete'),
    # temas
    path('temas_list/', views.tema_list_view, name='temas_list'),
    path('tema_create/', views.tema_create_view, name='tema_create'),
    path('tema_update/<int:pk>/', views.tema_update_view, name='tema_update'),
    path('tema_delete/<int:pk>/', views.tema_delete_view, name='tema_delete'),
    # projetomodelo
    path('projetomodelo_list/', views.projetomodelo_list_view, name='projetomodelo_list'),
    path('projeto_create/', views.projetomodelo_create_view, name='projeto_create'),
    path('projeto_update/<int:pk>/', views.projetomodelo_update_view, name='projeto_update'),
    path('projeto_delete/<int:pk>/', views.projetomodelo_delete_view, name='projeto_delete'),
    # turmas
    path('turmas_list/', views.turmas_list_view, name='turmas_list'),
    path('turma_create/', views.turmas_create_view, name='turma_create'),
    path('turma_update/<int:pk>/', views.turmas_update_view, name='turma_update'),
    path('turma_delete/<int:pk>/', views.turmas_delete_view, name='turma_delete'),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    # homepage
    path('', views.HomePageDetail, name='home'),
    # noticia
    path('noticia_detail/<int:pk>/', views.noticia_detail_view, name='noticia_detail'),
    path('noticias_list/', views.noticias_list_view, name='noticias_list'),
]

progressus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('users/', include('users.urls', namespace='users')),
    path('cadastros/', include('cadastros.urls', namespace='cadastros')),
    path('chamadas/',include('chamadas.urls', namespace='chamadas')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('profile/', views.profile_update_view, name='profile'),
    path('reset_password/', views.PasswordReset.as_view(), name="reset_password"),
    path('reset_password_sent/', views.PasswordResetDone.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(),name="password_reset_confirm"),
    path('reset_password_complete/', views.PasswordResetComplete.as_view(), name="password_reset_complete"),
    path('send_mail/<int:pk>/', views.enviar_email, name='send_mail'),
]

cadastros/models.py
from chamadas.models import Chamada, ProjetoModelo, Tema, Turma
from users.models import Profile
from pages.models import Noticia
from django.db import models

# Create your models here.

class CadastroProfile(models.Model):
    profile = models.OneToOneField(Profile, on_delete=models.CASCADE)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    def __str__(self):
        return self.profile

class CadastroChamada(models.Model):
    chamada = models.OneToOneField(Chamada, on_delete=models.CASCADE)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    def __str__(self):
        return self.chamada.nome

class CadastroNoticia(models.Model):
    noticia = models.OneToOneField(Noticia, on_delete=models.CASCADE)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    def __str__(self):
        return self.noticia.titulo

class CadastroTema(models.Model):
    tema = models.OneToOneField(Tema, on_delete=models.CASCADE)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    def __str__(self):
        return self.tema.titulo

class CadastroProjeto(models.Model):
    projeto = models.OneToOneField(ProjetoModelo, on_delete=models.CASCADE)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    def __str__(self):
        return self.projeto.nome

class CadastroTurma(models.Model):
    turma = models.OneToOneField(Turma, on_delete=models.CASCADE)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    def __str__(self):
        return self.turma.nome

cadastros/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from chamadas.forms import ChamadaFormCreate, ChamadaFormUpdate, ProjetoModeloForm, TemaFormCreate, TemaFormUpdate, ProjetoModeloUpdateForm, TurmaFormCreate, TurmaFormUpdate
from chamadas.models import Chamada, ProjetoModelo
from pages.forms import NoticiaFormCreate, NoticiaFormUpdate
from .models import CadastroChamada, CadastroProfile, CadastroNoticia, CadastroProjeto, CadastroTema, CadastroTurma
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, user_passes_test

# Create your views here.

# perfis

@login_required
@user_passes_test(lambda u:u.is_superuser, login_url='users:login')
def perfis_list_view(request):

    template_name = 'cadastros/profiles_list.html'

    object_list = CadastroProfile.objects.all()

    context = {'object_list': object_list}

    return render(request, template_name, context)

@login_required
@user_passes_test(lambda u:u.is_superuser, login_url='users:login')
def perfis_delete_view(request, pk):

    template_name = 'cadastros/forms_delete.html'

    object = get_object_or_404(User, pk = pk)

    if request.method == 'POST':
        object.delete()
        return HttpResponseRedirect(reverse_lazy('cadastros:profiles_list'))

    context = {'object': object}

    return render(request, template_name, context)

# chamadas

@login_required
@user_passes_test(lambda u:u.is_superuser, login_url='users:login')
def chamadas_create_view(request):

    template_name = 'cadastros/forms_upload.html'

    object_list = ProjetoModelo.objects.all()

    if object_list:
        pass
    else:
        ProjetoModelo.objects.create(nome = 'Padrão')
        projeto = ProjetoModelo.objects.get(nome = 'Padrão')
        CadastroProjeto.objects.create(projeto = projeto)

    if request.method == 'POST':
        form = ChamadaFormCreate(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            CadastroChamada.objects.create(chamada = form.instance)
            return HttpResponseRedirect(reverse_lazy('cadastros:chamadas_list'))
    else:
        form = ChamadaFormCreate()

    context = {'titulo': 'Novo cadastro de chamada', 'botao': 'Inscrever' ,'form': form}

    return render(request, template_name, context)

@login_required
@user_passes_test(lambda u:u.is_superuser, login_url='users:login')
def chamadas_list_view(request):

    template_name = 'cadastros/chamadas_list.html'

    object_list = CadastroChamada.objects.all()

    context = {'object_list': object_list}

    return render(request, template_name, context)

@login_required
@user_passes_test(lambda u:u.is_superuser, login_url='users:login')
def chamada_update_view(request, pk):

    template_name = 'cadastros/forms_upload.html'

    object = get_object_or_404(CadastroChamada, pk = pk)

    if request.method == 'POST':
        form = ChamadaFormUpdate(request.POST, request.FILES, instance=object.chamada)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse_lazy('cadastros:chamadas_list'))
    else:
        form = ChamadaFormUpdate(instance=object.chamada)

    context = {'titulo': 'Edição de cadastro de chamada', 'botao': 'Salvar', 'form': form}

    return render(request, template_name, context)

@login_required
@user_passes_test(lambda u:u.is_superuser, login_url='users:login')
def chamada_delete_view(request, pk):

    template_name = 'cadastros/forms_delete.html'

    object = get_object_or_404(CadastroChamada, pk = pk)

    if request.method == 'POST':
        object.chamada.delete()
        return HttpResponseRedirect(reverse_lazy('cadastros:chamadas_list'))

    context = {'object': object}

    return render(request, template_name, context)

# Notícias

@login_required
@user_passes_test(lambda u:u.is_superuser, login_url='users:login')
def noticia_create_view(request):

    template_name = 'cadastros/forms_upload.html'

    if request.method == 'POST':
        form = NoticiaFormCreate(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            CadastroNoticia.objects.create(noticia = form.instance)
            return HttpResponseRedirect(reverse_lazy('cadastros:noticias_list'))
    else:
        form = NoticiaFormCreate

    context = {'titulo': 'Novo cadastro de chamada', 'botao': 'Inscrever' ,'form': form}

    return render(request, template_name, context)

@login_required
@user_passes_test(lambda u:u.is_superuser, login_url='users:login')
def noticia_list_view(request):

    template_name = 'cadastros/noticias_list.html'

    object_list = CadastroNoticia.objects.all()

    context = {'object_list': object_list}

    return render(request, template_name, context)

@login_required
@user_passes_test(lambda u:u.is_superuser, login_url='users:login')
def noticia_update_view(request, pk):

    template_name = 'cadastros/forms_upload.html'

    object = get_object_or_404(CadastroNoticia, pk = pk)

    if request.method == 'POST':
        form = NoticiaFormUpdate(request.POST, request.FILES, instance=object.noticia)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse_lazy('cadastros:noticias_list'))
    else:
        form = NoticiaFormUpdate(instance=object.noticia)

    context = {'titulo': 'Edição de cadastro de chamada', 'botao': 'Salvar', 'form': form}

    return render(request, template_name, context)

@login_required
@user_passes_test(lambda u:u.is_superuser, login_url='users:login')
def noticia_delete_view(request, pk):

    template_name = 'cadastros/forms_delete.html'

    object = get_object_or_404(CadastroNoticia, pk = pk)

    if request.method == 'POST':
        object.noticia.delete()
        return HttpResponseRedirect(reverse_lazy('cadastros:noticias_list'))

    context = {'object': object}

    return render(request, template_name, context)

# Temas

@login_required
@user_passes_test(lambda u: u.is_superuser, login_url='users:login')
def tema_create_view(request):

    template_name = 'cadastros/forms.html'

    if request.method == 'POST':
        form = TemaFormCreate(request.POST)
        if form.is_valid():
            form.save() # criando objeto Tema
            CadastroTema.objects.create(tema = form.instance) # criando objeto CadastroTema
            return HttpResponseRedirect(reverse_lazy('cadastros:temas_list'))
    else:
        form = TemaFormCreate()

    context = {'titulo': 'Novo cadastro de tema', 'botao': 'Salvar', 'form': form}

    return render(request, template_name, context)

@login_required
@user_passes_test(lambda u: u.is_superuser, login_url='users:login')
def tema_list_view(request):

    template_name = 'cadastros/temas_list.html'

    object_list = CadastroTema.objects.all()

    context = {'object_list': object_list}

    return render(request, template_name, context)

@login_required
@user_passes_test(lambda u: u.is_superuser, login_url='users:login')
def tema_update_view(request, pk):

    template_name = 'cadastros/forms.html'

    object = get_object_or_404(CadastroTema, pk = pk)

    if request.method == 'POST':
        form = TemaFormUpdate(request.POST, instance = object.tema)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse_lazy('cadastros:temas_list'))
    else:
        form = TemaFormUpdate(instance=object.tema)

    context = {'titulo': 'Edição de cadastro de tema', 'botao': 'Salvar', 'form': form}

    return render(request, template_name, context)

@login_required
@user_passes_test(lambda u: u.is_superuser, login_url='users:login')
def tema_delete_view(request, pk):

    template_name = 'cadastros/forms_delete.html'

    object = get_object_or_404(CadastroTema, pk = pk)

    if request.method == 'POST':
        object.tema.delete()
        return HttpResponseRedirect(reverse_lazy('cadastros:temas_list'))

    context = {'object': object}

    return render(request, template_name, context)

# Projeto modelo

@login_required
@user_passes_test(lambda u:u.is_superuser, login_url='users:login')
def projetomodelo_list_view(request):

    template_name = 'cadastros/projetomodelo_list.html'

    object_list = CadastroProjeto.objects.all()

    context = {'object_list': object_list}

    return render(request, template_name, context)

@login_required
@user_passes_test(lambda u:u.is_superuser, login_url='users:login')
def projetomodelo_create_view(request):

    template_name = 'cadastros/forms.html'

    if request.method == 'POST':
        form = ProjetoModeloForm(request.POST)
        if form.is_valid():
            form.save()
            CadastroProjeto.objects.create(projeto = form.instance)
            return HttpResponseRedirect(reverse_lazy('cadastros:projetomodelo_list'))
    else:
        form = ProjetoModeloForm()

    context = {'titulo': 'Novo cadastro de modelo de projeto', 'botao': 'Salvar', 'form': form}

    return render(request, template_name, context)

@login_required
@user_passes_test(lambda u:u.is_superuser, login_url='users:login')
def projetomodelo_update_view(request, pk):

    template_name = 'cadastros/forms.html'

    object = get_object_or_404(CadastroProjeto, pk = pk)

    if request.method == 'POST':
        form = ProjetoModeloUpdateForm(request.POST, instance = object.projeto)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse_lazy('cadastros:projetomodelo_list'))
    else:
        form = ProjetoModeloUpdateForm(instance = object.projeto)

    context = {'titulo': 'Edição de cadastro de modelo de projeto', 'botao': 'Salvar', 'form': form}

    return render(request, template_name, context)

@login_required
@user_passes_test(lambda u: u.is_superuser, login_url='users:login')
def projetomodelo_delete_view(request, pk):

    template_name = 'cadastros/forms_delete.html'

cadastros/templates/cadastros/chamadas_list.html
{% extends 'pages/base.html' %}

{% load static %}

{% block content %}
    <div class="container-fluid">
        <h3 style="text-align: left;">
            Lista de chamadas
            <a class="btn btn-primary btn-sm float-end" href="{% url 'cadastros:chamada_create' %}">Adicionar</a>
        </h3>
        <div class="table-responsive">
            <table class="table table-striped" style="text-align: center;">
                <colgroup>
                    <col style="width: 20vw;">
                    <col style="width: 10vw;">
                    <col style="width: 10vw;">
                    <col style="width: 10vw;">
                    <col style="width: 10vw;">
                    <col style="width: 10vw;">
                    <col style="width: 10vw;">
                    <col style="width: 20vw;">
                </colgroup>
                <tr>
                    <th>Nome</th>
                    <th>Data</th>
                    <th>Atualização</th>
                    <th>Status</th>
                    <th>Orçamento</th>
                    <th>Projeto</th>
                    <th>Edital</th>
                    <th>Opções</th>
                </tr>
                {% for object in object_list %}
                    <tr>
                        <td>{{ object }}</td>
                        <td>{{ object.created|date:"d/m/Y" }}</td>
                        <td>{{ object.updated|date:"d/m/Y" }}</td>
                        <td>{{ object.chamada.get_status }}</td>
                        <td>{{ object.chamada.orcamento }}</td>
                        <td>{{ object.chamada.projetomodelo }}</td>
                        <td><a class="btn btn-primary btn-sm" href="{{ object.chamada.edital.url }}">Ver</a></td>
                        <td>
                            <a class="btn btn-warning btn-sm" href="{% url 'cadastros:chamada_update' object.pk %}">Editar</a>
                            <a class="btn btn-danger btn-sm" href="{% url 'cadastros:chamada_delete' object.pk %}">Excluir</a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="8" style="text-align: center;">Nenhuma chamada registrada até o momento.</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

{% block footnote %}
{% endblock %}

cadastros/templates/cadastros/forms.html
{% extends 'pages/base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <h3>{{ titulo }}</h3>
        <p class="lead">
            Preencha todos os campos obrigatórios.
        </p>
        <hr class="mt-4">
        <div class="col-md-6 mx-auto">
            <form action="" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary btn-sm mt-3">
                    {{ botao }}
                </button>
            </form>
            <br>
        </div>
    </div>
{% endblock %}

{% block footnote %}
{% endblock %}

cadastros/templates/cadastros/forms_delete.html
{% extends 'pages/base.html' %}

{% load static %}

{% block content %}
    <div class="container col-xl-6">
        {% if depend is not None %}
            <p style="color: red;"><strong>Erro!</strong></p>
            <p>Não foi possível excluir <strong>{{ object }}</strong>, devido a dependência com <strong>{{ depend }}.</strong></p>
        {% else %}
            <h3>Exclusão de registro</h3>
            <p class="lead">Confirme abaixo para excluir o registro definitivamente.</p>
            <hr>
            <form action="" method="POST">
                <p>Deseja realmente excluir <strong>{{ object }}</strong>? Esta ação será  definitiva!</p>
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-danger" type="submit">
                    Excluir
                </button>
            </form>
        {% endif %}
    </div>
{% endblock %}

{% block footnote %}
{% endblock %}

cadastros/templates/cadastros/forms_upload.html
{% extends 'pages/base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <h3>{{ titulo }}</h3>
        <p class="lead">
            Preencha todos os campos obrigatórios.
        </p>
        <hr class="mt-4">
        <div class="col-md-6 mx-auto">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary btn-sm mt-3">
                    {{ botao }}
                </button>
            </form>
            <br>
        </div>
    </div>
{% endblock %}

{% block footnote %}
{% endblock %}

cadastros/templates/cadastros/noticias_list.html
{% extends 'pages/base.html' %}

{% load static %}

{% block content %}
    <div class="container-fluid">
        <h3 style="text-align: left;">
            Lista de Notícias
            <a class="btn btn-primary btn-sm float-end" href="{% url 'cadastros:noticias_create' %}">Adicionar</a>
        </h3>
        <div class="table-responsive">
            <table class="table table-striped" style="text-align: left;">
                <colgroup>
                    <col style="width: 10vw;">
                    <col style="width: 70vw;">
                    <col style="width: 10vw;">
                    <col style="width: 10vw;">
                </colgroup>
                <tr>
                    <th>Título</th>
                    <th>Texto</th>
                    <th>Imagem</th>
                    <th>Opções</th>
                </tr>
                {% for object in object_list %}
                    <tr>
                        <td>{{ object }}</td>
                        <td>{{ object.noticia.texto|linebreaks|truncatewords:5 }}</td>
                        <td><a class="btn btn-primary btn-sm" href="{{ object.noticia.imagem.url }}">Ver</a></td>
                        <td>
                            <a class="btn btn-warning btn-sm" href="{% url 'cadastros:noticias_update' object.pk %}">Editar</a>
                            <a class="btn btn-danger btn-sm" href="{% url 'cadastros:noticias_delete' object.pk %}">Excluir</a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="4" style="text-align: center;">Nenhuma notícia registrada.</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

{% block footnote %}
{% endblock %}

cadastros/templates/cadastros/profiles_list.html
{% extends 'pages/base.html' %}

{% load static %}

{% block content %}
    <div class="container-fluid">
        <h3 style="text-align: center;">Lista de perfis</h3>
        <div class="table-responsive">
            <table class="table table-striped" style="text-align: center;">
                <colgroup>
                    <col style="width: 15vw;">
                    <col style="width: 20vw;">
                    <col style="width: 20vw;">
                    <col style="width: 20vw;">
                    <col style="width: 5vw;">
                    <col style="width: 10vw;">
                    <col style="width: 10vw;">
                </colgroup>
                <tr>
                    <th>Nome completo</th>
                    <th>Data</th>
                    <th>Username</th>
                    <th>email</th>
                    <th>turma</th>
                    <th>Status</th>
                    <th>Opções</th>
                </tr>
                {% for object in object_list %}
                <tr>
                    <td>{{ object.profile.nome_completo|default:'-' }}</td>
                    <td>{{ object.created }}</td>
                    <td>{{ object.profile.usuario }}</td>
                    <td><a href="{% url 'users:send_mail' object.pk %}">{{ object.profile.usuario.email }}</a></td>
                    <td>{{ object.profile.turma|default:'-' }}</td>
                    <td>{{ object.profile.profile_status|default:'-' }}</td>
                    <td><a class="btn btn-danger btn-sm" href="{% url 'cadastros:profile_delete' object.profile.usuario.pk %}">Excluir</a></td>
                </tr>
                {% empty %}
                    <tr>
                        <td colspan="6">Nenhum perfil registrado.</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

{% block footnote %}
{% endblock %}

cadastros/templates/cadastros/projetomodelo_list.html
{% extends 'pages/base.html' %}

{% load static %}

{% block content %}
    <div class="container-fluid">
        <h3 style="text-align: left;">
            Lista de modelos de projeto
            <a class="btn btn-primary btn-sm float-end" href="{% url 'cadastros:projeto_create' %}">Adicionar</a>
        </h3>
        <div class="table-responsive">
            <table class="table table-striped" style="text-align: center;">
                <colgroup>
                    <col style="width: 25vw;">
                    <col style="width: 25vw;">
                    <col style="width: 25vw;">
                    <col style="width: 25vw;">
                </colgroup>
                <tr>
                    <th>Nome</th>
                    <th>Data</th>
                    <th>Atualização</th>
                    <th>Opções</th>
                </tr>
                {% for object in object_list %}
                    <tr>
                        <td>{{ object }}</td>
                        <td>{{ object.created }}</td>
                        <td>{{ object.updated }}</td>
                        <td>
                            <a class="btn btn-warning btn-sm" href="{% url 'cadastros:projeto_update' object.pk %}">Editar</a>
                            {% if chamada.projetomodelo != object.projeto %}
                                <a class="btn btn-danger btn-sm" href="{% url 'cadastros:projeto_delete' object.pk %}">Excluir</a>
                            {% endif %}
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="6" style="text-align: center;">
                            Nenhuma modelo de projeto registrado até o momento.
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

{% block footnote %}
{% endblock %}

cadastros/templates/cadastros/temas_list.html
{% extends 'pages/base.html' %}

{% load static %}

{% block content %}
    <div class="container-fluid">
        <h3 style="text-align: left;">
            Lista de Temas
            <a class="btn btn-sm btn-primary float-end" href="{% url 'cadastros:tema_create' %}">Adicionar</a>
        </h3>
        <div class="table-responsive">
            <table class="table table-striped" style="text-align: center;">
                <colgroup>
                    <col style="width: 30vw;">
                    <col style="width: 25vw;">
                    <col style="width: 25vw;">
                    <col style="width: 20vw;">
                </colgroup>
                <tr>
                    <th>Título</th>
                    <th>Data</th>
                    <th>Atualizado</th>
                    <th>Opções</th>
                </tr>
                {% for object in object_list %}
                    <tr>
                        <td>{{ object }}</td>
                        <td>{{ object.created }}</td>
                        <td>{{ object.updated }}</td>
                        <td>
                            <a class="btn btn-sm btn-warning" href="{% url 'cadastros:tema_update' object.pk %}">Editar</a>
                            <a class="btn btn-sm btn-danger" href="{% url 'cadastros:tema_delete' object.pk %}">Excluir</a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="1">Nenhum tema registrado.</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

{% block footnote %}
{% endblock %}

cadastros/templates/cadastros/turmas_list.html
{% extends 'pages/base.html' %}

{% load static %}

{% block content %}
    <div class="container-fluid">
        <h3 style="text-align: left;">
            Lista de Turmas
            <a class="btn btn-sm btn-primary float-end" href="{% url 'cadastros:turma_create' %}">Adicionar</a>
        </h3>
        <div class="table-responsive">
            <table class="table table-striped" style="text-align: center;">
                <colgroup>
                    <col style="width: 30vw;">
                    <col style="width: 15vw;">
                    <col style="width: 25vw;">
                    <col style="width: 20vw;">
                    <col style="width: 20vw;">
                </colgroup>
                <tr>
                    <th>Turma</th>
                    <th>Total de alunos</th>
                    <th>Data</th>
                    <th>Atualizado</th>
                    <th>Opções</th>
                </tr>
                {% for object in object_list %}
                    <tr>
                        <td>{{ object }}</td>
                        <td>{{ object.turma.total_alunos }}</td>
                        <td>{{ object.created }}</td>
                        <td>{{ object.updated }}</td>
                        <td>
                            <a class="btn btn-sm btn-warning" href="{% url 'cadastros:turma_update' object.pk %}">Editar</a>
                            <a class="btn btn-sm btn-danger" href="{% url 'cadastros:turma_delete' object.pk %}">Excluir</a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="5">Nenhuma turma registrada até o momento.</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

{% block footnote %}
{% endblock %}