chamadas/urls.py
from django.urls import path
from . import views

app_name = 'chamadas'

urlpatterns = [
    # chamada
    path('chamadas_abertas/', views.abertas_list_view,name='chamadas_abertas'),
    path('chamadas_andamento/', views.andamento_list_view, name='chamadas_andamento'),
    path('chamadas_encerradas/', views.encerradas_list_view, name='chamadas_encerradas'),
    path('chamadas_list_superuser/', views.chamada_list_superuser_view, name='chamadas_list_superuser'),
    path('inscricao_list_user/', views.inscricao_list_user, name='inscricao_list_user'),
    # inscricao
    path('chamada_inscricao/<int:pk>/', views.inscricao_create_view, name='chamada_inscricao'),
    path('inscricoes_list_superuser/<int:pk>/', views.inscricao_list_superuser, name='inscricoes_list_superuser'),
    path('inscricao_delete/<int:pk>/', views.inscricao_delete_superuser, name='inscricao_delete'),
    path('inscricao_update/<int:pk>/', views.inscricao_update_view, name='inscricao_update'),
    path('inscricao_sendmail/<int:pk>/', views.enviar_email, name='inscricao_sendmail'),
    path('inscricao_sendmassmail/<int:pk>/', views.enviar_email_coletivo, name='inscricao_sendmassmail'),
    path('inscricao_detail/<int:pk>/', views.inscricao_detail_view, name='inscricao_detail'),
    # projeto
    path('projetos_list/<int:pk>/', views.projeto_list_view, name='projetos_list'),
    path('projeto_detail_superuser/<int:pk>/', views.projeto_detail_list_view, name='projeto_detail_superuser'),
    path('bibliografia_detail_superuser/<int:pk>/', views.bibliografia_detail_superuser, name='bibliografia_detail_superuser'),
    path('introducao_detail_superuser/<int:pk>/', views.introducao_detail_superuser, name='introducao_detail_superuser'),
    path('teoria_detail_superuser/<int:pk>/', views.teoria_detail_superuser, name='teoria_detail_superuser'),
    path('metodologia_detail_superuser/<int:pk>/', views.metodologia_detail_superuser, name='metodologia_detail_superuser'),
    path('resultado_detail_superuser/<int:pk>/', views.resultado_detail_superuser, name='resultado_detail_superuser'),
    path('apresentacao_detail_superuser/<int:pk>/', views.apresentacao_detail_superuser, name='apresentacao_detail_superuser'),
    path('financeiro_detail_superuser/<int:pk>/', views.financeiro_detail_superuser, name='financeiro_detail_superuser'),
    path('proposta_detail_superuser/<int:pk>/', views.proposta_detail_superuser, name='proposta_detail_superuser'),
    path('extra_detail_superuser/<int:pk>/', views.extra_detail_superuser, name='extra_detail_superuser'),
    # inscricao-usuario
    path('inscricao_extra/<int:pk>/', views.inscricao_extra_view, name='inscricao_extra'),
    path('inscricao_proposta/<int:pk>/', views.inscricao_proposta_view, name='inscricao_proposta'),
    path('inscricao_financeiro/<int:pk>/', views.inscricao_financeiro_view, name='inscricao_financeiro'),
    path('inscricao_apresentacao/<int:pk>/', views.inscricao_apresentacao_view, name='inscricao_apresentacao'),
    path('inscricao_bibliografia/<int:pk>/', views.inscricao_bibliografia_view, name='inscricao_bibliografia'),
    path('inscricao_projeto/<int:pk>/', views.inscricao_projeto_view, name='inscricao_projeto'),
    path('inscricao_introducao/<int:pk>/', views.inscricao_introducao_view, name='inscricao_introducao'),
    path('inscricao_status/<int:pk>/', views.inscricao_update_status_view, name='inscricao_status'),
    path('ranking_list/<int:pk>/', views.ranking_list, name='ranking_list'),
    path('projetos_destaque_list/<int:pk>/', views.projetos_destaque_list_view, name='projetos_destaque_list'),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    # homepage
    path('', views.HomePageDetail, name='home'),
    # noticia
    path('noticia_detail/<int:pk>/', views.noticia_detail_view, name='noticia_detail'),
    path('noticias_list/', views.noticias_list_view, name='noticias_list'),
]

progressus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('users/', include('users.urls', namespace='users')),
    path('cadastros/', include('cadastros.urls', namespace='cadastros')),
    path('chamadas/',include('chamadas.urls', namespace='chamadas')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('profile/', views.profile_update_view, name='profile'),
    path('reset_password/', views.PasswordReset.as_view(), name="reset_password"),
    path('reset_password_sent/', views.PasswordResetDone.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(),name="password_reset_confirm"),
    path('reset_password_complete/', views.PasswordResetComplete.as_view(), name="password_reset_complete"),
    path('send_mail/<int:pk>/', views.enviar_email, name='send_mail'),
]

chamadas/views.py
from datetime import date
from django.shortcuts import render, get_object_or_404
from chamadas.models import Apresentacao, Bibliografia, Chamada, Financeiro, Inscricao, Introducao, Metodologia, Projeto, Proposta, Resultado, Teoria, Extra
from chamadas.forms import BibliografiaForm, FinanceiroForm, InscricaoForm, InscricaoUpdateForm, ProjetoApresentacaoAdmin, ProjetoBibliografiaAdmin, ProjetoExtraAdmin, ProjetoFinanceiroAdmin, ProjetoForm, ProjetoIntroducaoAdmin, ProjetoPropostaAdmin, ProjetoTituloForm, PropostaForm, InscricaoStatusAdmin
from chamadas.forms import ProjetoTeoriaAdmin, ProjetoResultadoAdmin
from chamadas.forms import ProjetoMetodologiaAdmin
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required, user_passes_test
from progressus.settings import EMAIL_HOST_USER, MEDIA_ROOT
from django.core.mail import send_mail
from chamadas.utils import Valor

# Chamada

def abertas_list_view(request):

    template_name = 'chamadas/chamadas_abertas.html'

    object_list = [object for object in Chamada.objects.all() if object.get_status() == 'Aberto']

    context = {'object_list': object_list}

    return render(request, template_name, context)

def andamento_list_view(request):

    template_name = 'chamadas/chamadas_andamento.html'

    object_list = [object for object in Chamada.objects.all() if object.get_status() == 'Em andamento']

    context = {'object_list': object_list}

    return render(request, template_name, context)

def projetos_destaque_list_view(request, pk):

    template_name = 'chamadas/projetos_destaque_list.html'

    chamada = get_object_or_404(Chamada, pk = pk)

    inscricao = Inscricao.objects.filter(chamada = chamada)

    object_list = [object for object in inscricao if object.inscricao_status == 'destaque']

    context = {'object_list': object_list, 'chamada': chamada}

    return render(request, template_name, context)

def encerradas_list_view(request):

    template_name = 'chamadas/chamadas_encerradas.html'

    object_list = [object for object in Chamada.objects.all() if object.get_status() == 'Encerrado']

    context = {'object_list': object_list}

    return render(request, template_name, context)

@login_required
@user_passes_test(lambda u: u.is_superuser, login_url='users:login')
def chamada_list_superuser_view(request):

    template_name = 'chamadas/chamadas_list_superuser.html'

    object_list = Chamada.objects.all()

    context = {'object_list': object_list}

    return render(request, template_name, context)

# Inscricao

@login_required
def inscricao_create_view(request, pk):

    template_name = 'chamadas/inscricao_form.html'

    chamada = get_object_or_404(Chamada, pk = pk)

    if Inscricao.objects.filter(lider = request.user.profile, chamada = chamada).exists():
        context = {'chamada': chamada}
        return render(request, 'chamadas/inscricao_erro.html', context)
    else:
        if request.method == 'POST':
            form = InscricaoForm(request.POST)
            if form.is_valid():
                form.instance.chamada = chamada
                form.instance.lider = request.user.profile
                form.save()
                Projeto.objects.create(inscricao = form.instance, modelo = chamada.projetomodelo)
                Bibliografia.objects.create(inscricao = form.instance, modelo = chamada.projetomodelo)
                Apresentacao.objects.create(inscricao = form.instance, modelo = chamada.projetomodelo)
                Proposta.objects.create(inscricao = form.instance, modelo = chamada.projetomodelo)
                Extra.objects.create(inscricao = form.instance)
                Financeiro.objects.create(inscricao = form.instance)
                projeto = Projeto.objects.get(inscricao = form.instance)
                Introducao.objects.create(projeto = projeto)
                Teoria.objects.create(projeto = projeto)
                Metodologia.objects.create(projeto = projeto)
                Resultado.objects.create(projeto = projeto)
                sender = EMAIL_HOST_USER
                receiver = form.instance.lider.usuario.email
                message = (
                        'Inscrição feita com sucesso na chamada {} em {}.\n\n'.format(form.instance.chamada, form.instance.created)+
                        'Equipe: {}\n'.format(form.instance.equipe)+
                        'Turma: {}\n'.format(form.instance.turma)+
                        'Lider: {}\n'.format(form.instance.lider)+
                        'Membro: {}\n'.format(form.instance.membro_1)+
                        'Membro: {}\n'.format(form.instance.membro_2)+
                        'Membro: {}\n'.format(form.instance.membro_3)+
                        '\nPara maiores informações, acesse http://200.17.101.198/'
                        )
                subject = 'Plaforma progressus - Inscrição'
                send_mail(subject, message, sender, [receiver], fail_silently=False)
                return HttpResponseRedirect(reverse_lazy('chamadas:chamadas_abertas'))
        else:
            form = InscricaoForm()
            form.instance.lider = request.user.profile

        context = {'botao': 'Inscrever', 'chamada': chamada ,'form': form}
        return render(request, template_name, context)

@login_required
@user_passes_test(lambda u: u.is_superuser, login_url='users:login')
def inscricao_list_superuser(request, pk):

    template_name = 'chamadas/inscricoes_list_superuser.html'

    chamada = get_object_or_404(Chamada, pk = pk)

    object_list = Inscricao.objects.filter(chamada = chamada)

    context = {'object_list': object_list, 'chamada': chamada}

    return render(request, template_name, context)

@login_required
@user_passes_test(lambda u: u.is_superuser, login_url='users:login')
def inscricao_delete_superuser(request, pk):

    template_name = 'cadastros/forms_delete.html'

    object = get_object_or_404(Inscricao, pk = pk)

    if request.method == 'POST':
        object.delete()
        return HttpResponseRedirect(reverse_lazy('chamadas:inscricoes_list_superuser', kwargs = {'pk': object.chamada.pk}))

    context = {'object': object}

    return render(request, template_name, context)

@login_required
@user_passes_test(lambda u: u.is_superuser, login_url='users:login')
def inscricao_update_view(request, pk):

    template_name = 'chamadas/inscricao_editar.html'

    object = get_object_or_404(Inscricao, pk = pk)

    if request.method == 'POST':
        form = InscricaoUpdateForm(request.POST, instance=object)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse_lazy('chamadas:inscricoes_list_superuser', kwargs = {'pk': object.chamada.pk}))
    else:
        form = InscricaoUpdateForm(instance = object)

    context = {'botao': 'Editar', 'form': form}

    return render(request, template_name, context)

@login_required
@user_passes_test(lambda u: u.is_superuser, login_url='users:login')
def inscricao_update_status_view(request, pk):

    template_name = 'chamadas/inscricao_status_editar.html'

    object = get_object_or_404(Inscricao, pk = pk)

    if request.method == 'POST':
        form = InscricaoStatusAdmin(request.POST, instance=object)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse_lazy('chamadas:projetos_list', kwargs = {'pk': object.chamada.pk}))
    else:
        form = InscricaoStatusAdmin(instance = object)

    context = {'botao': 'Editar', 'form': form}

    return render(request, template_name, context)

@login_required
@user_passes_test(lambda u: u.is_superuser, login_url='users:login')
def enviar_email(request, pk):

    template_name = 'users/email.html'

    inscricao = get_object_or_404(Inscricao, pk = pk)

    sender = EMAIL_HOST_USER
    receiver = inscricao.lider.usuario.email
    subject = 'Plaforma progressus - Atenção!'

    if request.method == 'POST':
        message = request.POST.get('message')
        send_mail(subject, message, sender, [receiver], fail_silently=False)
        return HttpResponseRedirect(reverse_lazy('pages:home'))
    else:
        message = ''

    form = {'from': sender, 'to': receiver, 'message': message, 'subject': subject}

    context = {'nome': inscricao, 'botao': 'Enviar', 'form': form}

    return render(request, template_name, context)

@login_required
@user_passes_test(lambda u: u.is_superuser, login_url='users:login')
def enviar_email_coletivo(request, pk):

    template_name = 'users/email.html'

    chamada = get_object_or_404(Chamada, pk = pk)

    receiver = [u.lider.usuario.email for u in Inscricao.objects.filter(chamada = chamada)]

    sender = EMAIL_HOST_USER
    subject = 'Plaforma progressus - Atenção!'

    if request.method == 'POST':
        message = request.POST.get('message')
        send_mail(subject, message, sender, receiver, fail_silently=False)
        return HttpResponseRedirect(reverse_lazy('pages:home'))
    else:
        message = ''

    form = {'from': sender, 'to': receiver, 'message': message, 'subject': subject}

    context = {'chamada': chamada, 'botao': 'Enviar', 'form': form}

    return render(request, template_name, context)

@login_required
def inscricao_list_user(request):

    template_name = 'chamadas/inscricao_list_user.html'

    object_list = Inscricao.objects.filter(lider = request.user.profile)

    context = {'object_list': object_list}

    return render(request, template_name, context)

@login_required
def inscricao_detail_view(request, pk):

    template_name = 'chamadas/inscricao_detail.html'

    object = get_object_or_404(Inscricao, pk = pk, lider = request.user.profile)

    if request.method == 'POST':
        form = ProjetoTituloForm(request.POST, instance=object.projeto)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse_lazy('chamadas:inscricao_detail', kwargs = {'pk': pk}))
    else:

chamadas/templates/chamadas/chamadas_andamento.html
{% extends 'pages/base.html' %}

{% load static %}

{% block content %}
    <div class="container">
        <h3>Chamadas em andamento</h3>
        {% for object in object_list %}
            <h4>{{ object.nome }}</h4>
            <p><em>Atualizado em {{ object.cadastrochamada.updated }}</em></p>
            <p>
                Objetivos:
                <br>
                <em>{{ object.resumo }}</em>
            </p>
            <p>Data de encerramento: {{ object.deadline_chamada }}.</p>
            <p>
                <a class="btn btn-primary btn-sm" href="{{ object.edital.url }}">Edital</a>
            </p>
            {% if request.user.is_authenticated %}
                <p>
                    <a class="btn btn-primary btn-sm" href="{% url 'chamadas:ranking_list' object.pk %}">Ranking</a>
                </p>
            {% endif %}
            <p><a class="btn btn-primary btn-sm" href="{% url 'users:login' %}">Login</a></p>
        {% empty %}
            <p>Nenhuma chamada em andamento até o momento...</p>
        {% endfor %}
    </div>
{% endblock %}

chamadas/templates/chamadas/financeiro_detail.html
{% extends 'pages/base.html' %}

{% load widget_tweaks %}

{% block content %}
    <div class="container">
        <h2>Equipe: {{ form.instance.inscricao }}</h2>
        <div class="card-body">
            <h4 class="card-title text-center">Prestação de contas</h4>
            <form action="" method="POST">
                <div class="border">
                    {% csrf_token %}
                    <div class="mx-3 my-3 mt-3 mb-3">
                        <h5>Comprovantes</h5>
                        <div class="row">
                            <div class="col-sm-2">
                                <span>Comprovante 1:</span>
                            </div>
                            <div class="col-sm-2 mx-1">
                                <span>
                                    {% if form.instance.comprovante_1 %}
                                        <a href="{{ form.instance.comprovante_1.url }}">Ver</a>
                                    {% else %}
                                        <span class="col-sm-2">Sem comprovante</span>
                                    {% endif %}
                                </span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-2">
                                <span>Comprovante 2:</span>
                            </div>
                            <div class="col-sm-2 mx-1">
                                <span>
                                    {% if form.instance.comprovante_1 %}
                                        <a href="{{ form.instance.comprovante_1.url }}">Ver</a>
                                    {% else %}
                                        <span class="col-sm-2">Sem comprovante</span>
                                    {% endif %}
                                </span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-2">
                                <span>Comprovante 3:</span>
                            </div>
                            <div class="col-sm-2 mx-1">
                                {% if form.instance.comprovante_1 %}
                                <a href="{{ form.instance.comprovante_1.url }}">Ver</a>
                            {% else %}
                                <span class="col-sm-2">Sem comprovante</span>
                            {% endif %}
                        </div>
                        </div>
                        <hr>
                            <div class="row">
                                <label class="col-sm-2 col-form-label" for="">
                                    Considerações:
                                </label>
                                <div class="col-sm-6">
                                    {% render_field form.consideracoes class+="form-control" %}
                                </div>
                            </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary btn-sm mt-3">
                                Avaliar
                            </button>    
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block footnote %}
{% endblock %}

chamadas/templates/chamadas/inscricao_editar.html
{% extends 'pages/base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <h3>Edição da equipe <strong>{{ form.instance }}</strong>.</h3>
        <hr class="mt-4">
        <div class="col-md-6 mx-auto">
            <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group row">
                    <label for="lider" class="col-sm-2 col-form-label">Lider</label>
                    <div class="col-sm-10">
                        <input type="text" readonly class="form-control-plaintext" id="lider" value="{{ form.instance.lider }}">
                    </div>
                </div>
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary btn-sm mt-3">
                    {{ botao }}
                </button>
            </form>
            <br>
        </div>
    </div>
{% endblock %}

{% block footnote %}
{% endblock %}

chamadas/templates/chamadas/inscricao_introducao.html
{% extends 'pages/base.html' %}

{% load widget_tweaks %}

{% block content %}
    <div class="container">
        <h3>
            <form class="form-inline" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="projeto.titulo">Projeto:</label>
                    <input type="text" name="projeto" id="projeto" value="{{ form.instance.projeto.titulo }}">
                    <button type="submit" class="btn btn-sm btn-primary">Alterar nome</button>    
                </div>    
            </form>
        </h3>
        <div class="card-body">
            <h4 class="card-title text-center">Introdução</h4>
            <div class="table-responsive text-center">
                <table class="table table-striped">
                    <tr>
                        <th>Parâmetros de avaliação</th>
                        <th>Considerações do avaliador</th>
                        <th>Peso</th>
                        <th>Nota</th>
                    </tr>
                    <tr>
                        <td>{{ object.projeto.modelo.introducao_titulo_1 }}</td>
                        <td>{{ object.introducao_consideracoes_1|default:"Aguarde..." }}</td>
                        <td>{{ object.projeto.modelo.introducao_peso_1 }}</td>
                        <td>{{ object.introducao_nota_1 }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block footnote %}
{% endblock %}

chamadas/templates/chamadas/inscricao_list_user.html
{% extends 'pages/base.html' %}

{% load static %}

{% block content %}
    <div class="container col-xl-9 text-center">
        <h3>Minhas inscrições</h3>
        <hr>
        <div class="table-responsive">
            <table class="table table-striped">
                <tr>
                    <th>Chamada</th>
                    <th>Tema</th>
                    <th>Status</th>
                    <th>Data</th>
                    <th>Nome da equipe</th>
                </tr>
                {% for object in object_list %}
                    <tr>
                        <td>{{ object.chamada }}</td>
                        <td>{{ object.tema }}</td>
                        <td>{{ object.chamada.get_status}}</td>
                        <td>{{ object.created }}</td>
                        <td>
                            <a href="{% url 'chamadas:inscricao_detail' object.pk %}">{{ object.equipe }}</a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="6">Não há inscrições até o momento.</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

{% block footnote %}
{% endblock %}

chamadas/templates/chamadas/projetos_destaque_list.html
{% extends 'pages/base.html' %}

{% load static %}

{% block content %}
    <div class="container">
        <h3>Projetos em destaque da chamada <strong>{{ chamada }}</strong></h3>
        {% for object in object_list %}
            <h4>Equipe: {{ object }}</h4>
            <p>
                <p>Proposta:</p>
                <em>{{ object.proposta.conteudo }}</em>
            </p>
            <p>
                <a class="btn btn-primary btn-sm" href="{{ object.projeto.arquivo.url }}">Ver projeto</a>
            </p>
        {% empty %}
            <p>Nenhum projeto em destaque até o momento...</p>
    {% endfor %}
    </div>
{% endblock %}

chamadas/templates/chamadas/projetos_list.html
{% extends 'pages/base.html' %}

{% block content %}
    <div class="container-fluid text-center">
        <h3>
            Lista de projetos da chamada <strong>{{ chamada }}</strong>
            <span class="float-end">
                <form action="" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-sm btn-primary">Avaliar</button>
                </form>
            </span>    
        </h3>
        <div class="table-responsive">
            <table class="table table-striped">
                <colgroup>
                    <col style="width: 10vw;">
                    <col style="width: 10vw;">
                    <col style="width: 10vw;">
                    <col style="width: 10vw;">
                    <col style="width: 10vw;">
                    <col style="width: 10vw;">
                    <col style="width: 10vw;">
                    <col style="width: 10vw;">
                    <col style="width: 10vw;">
                    <col style="width: 10vw;">
                </colgroup>
                <tr>
                    <th>Equipe</th>
                    <th>Turma</th>
                    <th>
                        Rev. bib.
                        ({{ chamada.deadline_bibliografia|date:"d/m/y" }})
                    </th>
                    <th>
                        Proposta
                        ({{ chamada.deadline_proposta|date:"d/m/y" }})
                    </th>
                    <th>
                        Projeto
                        ({{ chamada.deadline_projeto|date:"d/m/y" }})
                    </th>
                    <th>
                        Apresentação
                        ({{ chamada.deadline_chamada|date:"d/m/y" }})
                    </th>
                    <th>Extra</th>
                    <th>
                        Financeiro
                        ({{ chamada.deadline_projeto|date:"d/m/y" }})
                    </th>
                    <th>Status</th>
                    <th>Nota</th>
                    {% for object in object_list %}
                        <tr>
                            <td>
                                <a href="{% url 'chamadas:inscricoes_list_superuser' chamada.pk %}">{{ object }}</a>
                            </td>
                            <td>{{ object.turma }}</td>
                            <td>
                                {% if object.bibliografia.updated > object.chamada.deadline_bibliografia %}
                                    <a style="color: blue;" href="{% url 'chamadas:bibliografia_detail_superuser' object.pk %}">
                                        {{ object.bibliografia.updated|date:"d/m/Y" }}
                                    </a>
                                {% else %}
                                    <a style="color: red;" href="{% url 'chamadas:bibliografia_detail_superuser' object.pk %}">
                                        {{ object.bibliografia.updated|date:"d/m/Y" }}
                                    </a>
                                {% endif %}
                            </td>
                            <td>
                                {% if object.proposta.updated > object.chamada.deadline_proposta %}
                                    <a style="color: blue;" href="{% url 'chamadas:proposta_detail_superuser' object.pk %}">
                                        {{ object.proposta.updated|date:"d/m/Y" }}
                                    </a>
                                {% else %}
                                    <a style="color: red;" href="{% url 'chamadas:proposta_detail_superuser' object.pk %}">
                                        {{ object.proposta.updated|date:"d/m/Y" }}
                                    </a>
                                {% endif %}
                            </td>
                            <td>
                                {% if object.projeto.updated > object.chamada.deadline_projeto %}
                                    <a style="color: blue;" href="{% url 'chamadas:projeto_detail_superuser' object.chamada.pk %}">
                                        {{ object.projeto.updated|date:"d/m/Y" }}
                                    </a>
                                {% else %}
                                    <a style="color: red;" href="{% url 'chamadas:projeto_detail_superuser' object.chamada.pk %}">
                                        {{ object.projeto.updated|date:"d/m/Y" }}
                                    </a>
                                {% endif %}
                            </td>
                            <td>
                                {% if object.apresentacao.updated > object.chamada.deadline_chamada %}
                                    <a style="color: blue;" href="{% url 'chamadas:apresentacao_detail_superuser' object.pk %}">
                                        {{ object.apresentacao.updated|date:"d/m/Y" }}
                                    </a>
                                {% else %}
                                    <a style="color: red;" href="{% url 'chamadas:apresentacao_detail_superuser' object.pk %}">
                                        {{ object.apresentacao.updated|date:"d/m/Y" }}
                                    </a>
                                {% endif %}
                            </td>
                            <td>
                                <a href="{% url 'chamadas:extra_detail_superuser' object.pk %}">
                                    {{ object.extra.updated|date:"d/m/Y" }}
                                </a>
                            </td>
                            <td>
                                {% if object.financeiro.updated > object.chamada.deadline_projeto %}
                                    <a style="color: blue;" href="{% url 'chamadas:financeiro_detail_superuser' object.pk %}">
                                        {{ object.financeiro.updated|date:"d/m/Y" }}
                                    </a>
                                {% else %}
                                    <a style="color: red;" href="{% url 'chamadas:financeiro_detail_superuser' object.pk %}">
                                        {{ object.financeiro.updated|date:"d/m/Y" }}
                                    </a>
                                {% endif %}
                            </td>
                            <td><a href="{% url 'chamadas:inscricao_status' object.pk %}">{{ object.getStatus }}</a></td>
                            <td>{{ object.nota }}</td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="9">Nenhum projeto está cadastrado nesta chamada.</td>
                        </tr>
                    {% endfor %}
                </tr>
            </table>
        </div>
    </div>
{% endblock %}

{% block footnote %}
{% endblock %}