pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    # homepage
    path('', views.HomePageDetail, name='home'),
    # noticia
    path('noticia_detail/<int:pk>/', views.noticia_detail_view, name='noticia_detail'),
    path('noticias_list/', views.noticias_list_view, name='noticias_list'),
]

progressus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('users/', include('users.urls', namespace='users')),
    path('cadastros/', include('cadastros.urls', namespace='cadastros')),
    path('chamadas/',include('chamadas.urls', namespace='chamadas')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('profile/', views.profile_update_view, name='profile'),
    path('reset_password/', views.PasswordReset.as_view(), name="reset_password"),
    path('reset_password_sent/', views.PasswordResetDone.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(),name="password_reset_confirm"),
    path('reset_password_complete/', views.PasswordResetComplete.as_view(), name="password_reset_complete"),
    path('send_mail/<int:pk>/', views.enviar_email, name='send_mail'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    nome_completo = models.CharField(max_length=50, null=True)
    turma = models.CharField(max_length=4, null=True)
    profile_status = models.CharField(
        max_length=10,
        default="Adimplente",
        choices=(("adimplente", "Adimplente"), ("em_debito", "Em débito"))
        )

    def __str__(self):
        return self.nome_completo

users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.core.exceptions import ValidationError
from users.models import Profile

class UserCreation(UserCreationForm):

    email = forms.EmailField(max_length=50)  

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'email']

    def clean_email(self):
        data = self.cleaned_data['email']
        if User.objects.filter(email=data).exists():
            raise ValidationError(" O email {} já está em uso.".format(data))
        return data

    def clean_username(self):
        data = self.cleaned_data['username']
        if User.objects.filter(username=data).exists():
            raise ValidationError(" O nome de usuário {} já está em uso.".format(data))
        return data

class ProfileCreation(forms.ModelForm):

    class Meta:
        model = Profile

        fields = ['nome_completo', 'turma']

users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from cadastros.models import CadastroProfile
from progressus.settings import EMAIL_HOST_USER
from users.forms import ProfileCreation, UserCreation
from django.contrib.auth.models import Group
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView, PasswordResetConfirmView
from django.views.generic.edit import CreateView
from users.models import Profile
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail

# Create your views here.

class UserCreateView(CreateView):
    template_name = "users/forms.html"
    form_class = UserCreation
    success_url = reverse_lazy("users:login")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = "Registro de novo usuário"
        context['botao'] = "Cadastrar"
        return context

    def form_valid(self, form):
        if Group.objects.filter(name="users").exists() == False:
            Group.objects.create(name="users")
        grupo = get_object_or_404(Group, name="users")
        url = super().form_valid(form)
        self.object.groups.add(grupo)
        self.object.save()
        profile = Profile.objects.create(usuario=self.object)
        CadastroProfile.objects.create(profile = profile)
        return url

#def user_create_view(request):
#    template_name = "users/forms.html"
#    form_class = UserCreation
#    form = form_class
#
#    if request.method == 'POST':
#        form = form_class(request.POST)
#        if form.is_valid():
#            form.save()
#            return HttpResponseRedirect(reverse_lazy('pages:home'))
#
#    context = {'titulo': 'Registro de cadastro de usuário', 'botao': 'Cadastrar', 'form': form}
#
#    return render(request, template_name, context)

@login_required
def profile_update_view(request):
    template_name = "users/forms.html"
    form_class = ProfileCreation
#
    object = get_object_or_404(Profile, usuario = request.user)
#
    if request.method == 'POST':
        form = form_class(request.POST, instance = object)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse_lazy('pages:home'))
    else:
        form = form_class(instance = object)
#
    context = {'titulo': 'Registro de cadastro de usuário', 'botao': 'Cadastrar', 'form': form}
#
    return render(request, template_name, context)

# reset de senha

class PasswordReset(PasswordResetView):
    template_name='users/password_reset.html'
    email_template_name='users/password_reset_email.html'
    success_url=reverse_lazy('users:password_reset_done')

class PasswordResetDone(PasswordResetDoneView):
    template_name='users/password_reset_done.html'

class PasswordResetConfirm(PasswordResetConfirmView):
    template_name='users/password_reset_confirm.html'
    success_url=reverse_lazy('users:password_reset_complete')

class PasswordResetComplete(PasswordResetCompleteView):
    template_name='users/password_reset_complete.html'

# email

def enviar_email(request, pk):

    template_name = 'users/email.html'

    usuario = get_object_or_404(Profile, pk = pk)

    sender = EMAIL_HOST_USER
    receiver = usuario.usuario.email
    subject = 'Plaforma progressus - Atenção!'

    if request.method == 'POST':
        message = request.POST.get('message')
        send_mail(subject, message, sender, [receiver], fail_silently=False)
        return HttpResponseRedirect(reverse_lazy('pages:home'))
    else:
        message = ''

    form = {'from': sender, 'to': receiver, 'message': message, 'subject': subject}

    context = {'nome': usuario.nome_completo, 'botao': 'Enviar', 'form': form}

    return render(request, template_name, context)

users/templates/users/email.html
{% extends 'pages/base.html' %}

{% block content %}
    <div class="container">
        <h3>Enviando de email para <strong>{{ nome }}</strong></h3>
        <hr class="mt-4">
        <div class="col-md-8 mx-auto">
            <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group row">
                    <label for="sender" class="col-sm-2 col-form-label">De</label>
                    <div class="col-sm-10">
                        <input type="text" readonly class="form-control-plaintext" id="sender" value="{{ form.from }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="receiver" class="col-sm-2 col-form-label">Para</label>
                    <div class="col-sm-8">
                      <input type="text" readonly class="form-control-plaintext" id="receiver" value="{{ form.to }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="subject" class="col-sm-2 col-form-label">Assunto</label>
                    <div class="col-sm-10">
                      <input type="text" readonly class="form-control-plaintext" id="subject" value="{{ form.subject }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="message" class="col-sm-2 col-form-label">Mensagem</label>
                    <div class="col-sm-10">
                        <textarea name="message" id="message" cols="70" rows="10">{{ form.message }}</textarea>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary btn-sm mt-3">{{ botao }}</button>
            </form>
            <br>
        </div>
    </div>
{% endblock %}

{% block footnote %}
{% endblock %}

users/templates/users/forms.html
{% extends 'pages/base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <h3>{{ titulo }}</h3>
        <p class="lead">
            Preencha todos os campos obrigatórios.
        </p>
        <hr class="mt-4">
        <div class="col-md-6 mx-auto">
            <form action="" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary btn-sm mt-3">
                    {{ botao }}
                </button>
            </form>
        </div>
    </div>
{% endblock %}

users/templates/users/login.html
{% extends 'pages/base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="row">
        {% if request.user.is_authenticated %}
            <div class="col-md mx-auto" style="text-align: center;">
                <h3><strong>Ação não permitida</strong></h3>
                <br>
                <p class="lead">Você não tem permissão para acessar esta página!</p>
            </div>
        {% else %}
            <div class="col-md-4 mx-auto">
                <h3 style="text-align: center;">Autenticação</h3>
                <hr>
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-primary mt-3">Entrar</button>
                </form>
                <br>
                <a href="{% url 'users:register' %}">Cadastre-se</a>
                <a class="float-end" href="{% url 'users:reset_password' %}">Esqueceu a senha?</a>
            </div>
        {% endif %}
    </div>
{% endblock %}

users/templates/users/password_reset.html
{% extends 'pages/base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block title %}Change Password Page{% endblock title %}

{% block content %}
    <div class="container">
        <h3>Recuperando senha</h3>
        <p class="lead" style="font-size: 10pt;">
            Esqueceu a senha? Forneça seu endereço de email abaixo (deve ser o mesmo da sua conta), e nós te enviaremos um email com instruções detalhadas para configurar uma nova.
        </p>
        <hr class="mt-4">
        <div class="col-md-3">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <br>
                <button type="submit" class="btn btn-primary btn-sm">Reinicializar minha senha</a>
            </form>    
        </div>
    </div>
{% endblock content %}

users/templates/users/password_reset_complete.html
{% extends 'pages/base.html' %}

{% load static %}

{% block title %}Change Password Page{% endblock title %}

{% block content %}
    <div class="container">
        <h4>Redefinição de senha completa</h4>
        <hr class="mt-4">
        <p>Sua senha foi redefinida com sucesso. Você pode prosseguir com a autenticação.</p>
        <a href="{% url 'users:login' %}">Acessar</a>
    </div>
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends 'pages/base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block title %}Change Password Page{% endblock title %}

{% block content %}
  <div class="container" style="font-size: 10pt;">
    <h4>Digite a nova senha</h4>
    <hr class="mt-4">
    <div class="col-md-7" style="flex-direction: column;">
      <div>
        <p>Por favor, informe sua nova senha duas vezes para que possamos verificar se você a digitou corretamente.</p>
      </div>
      <div>
        <form class="form" action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form|crispy }}
          <br>
        <button type="submit" class="btn btn-primary btn-lg btn-block btn-sm"><i class="icon-lock4"></i>Alterar senha</button>
        </form>  
      </div>
      <br>
    </div>
  </div>
{% endblock content %}

users/templates/users/password_reset_done.html
{% extends 'pages/base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h3>Redefinição de senha enviada</h3>
    <hr class="mt-4">
    <p>Nós te enviamos um email com instruções detalhadas para configurar sua senha, se uma conta existe com o email fornecido, você receberá a mensagem em breve. Se não recebeu um email, por favor certifique-se que forneceu o endereço que está cadastrado, e verifique sua pasta de spam.</p>
    {% endblock %}
</div>

{% block footnote %}
{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% endautoescape %}