cadastros/urls.py
from django.urls import path
from . import views

app_name = 'cadastros'

urlpatterns = [
    # perfis
    path('profiles_list/',views.perfis_list_view, name='profiles_list'),
    path('profile_delete/<int:pk>/', views.perfis_delete_view, name='profile_delete'),
    # chamadas
    path('chamadas_list/',views.chamadas_list_view, name='chamadas_list'),
    path('chamada_create/', views.chamadas_create_view, name='chamada_create'),
    path('chamada_delete/<int:pk>/', views.chamada_delete_view, name='chamada_delete'),
    path('chamada_update/<int:pk>/', views.chamada_update_view, name='chamada_update'),
    # noticias
    path('noticias_list/', views.noticia_list_view, name='noticias_list'),
    path('noticias_create/', views.noticia_create_view, name='noticias_create'),
    path('noticias_update/<int:pk>/', views.noticia_update_view, name='noticias_update'),
    path('noticias_delete/<int:pk>/', views.noticia_delete_view, name='noticias_delete'),
    # temas
    path('temas_list/', views.tema_list_view, name='temas_list'),
    path('tema_create/', views.tema_create_view, name='tema_create'),
    path('tema_update/<int:pk>/', views.tema_update_view, name='tema_update'),
    path('tema_delete/<int:pk>/', views.tema_delete_view, name='tema_delete'),
    # projetomodelo
    path('projetomodelo_list/', views.projetomodelo_list_view, name='projetomodelo_list'),
    path('projeto_create/', views.projetomodelo_create_view, name='projeto_create'),
    path('projeto_update/<int:pk>/', views.projetomodelo_update_view, name='projeto_update'),
    path('projeto_delete/<int:pk>/', views.projetomodelo_delete_view, name='projeto_delete'),
    # turmas
    path('turmas_list/', views.turmas_list_view, name='turmas_list'),
    path('turma_create/', views.turmas_create_view, name='turma_create'),
    path('turma_update/<int:pk>/', views.turmas_update_view, name='turma_update'),
    path('turma_delete/<int:pk>/', views.turmas_delete_view, name='turma_delete'),
]

chamadas/urls.py
from django.urls import path
from . import views

app_name = 'chamadas'

urlpatterns = [
    # chamada
    path('chamadas_abertas/', views.abertas_list_view,name='chamadas_abertas'),
    path('chamadas_andamento/', views.andamento_list_view, name='chamadas_andamento'),
    path('chamadas_encerradas/', views.encerradas_list_view, name='chamadas_encerradas'),
    path('chamadas_list_superuser/', views.chamada_list_superuser_view, name='chamadas_list_superuser'),
    path('inscricao_list_user/', views.inscricao_list_user, name='inscricao_list_user'),
    # inscricao
    path('chamada_inscricao/<int:pk>/', views.inscricao_create_view, name='chamada_inscricao'),
    path('inscricoes_list_superuser/<int:pk>/', views.inscricao_list_superuser, name='inscricoes_list_superuser'),
    path('inscricao_delete/<int:pk>/', views.inscricao_delete_superuser, name='inscricao_delete'),
    path('inscricao_update/<int:pk>/', views.inscricao_update_view, name='inscricao_update'),
    path('inscricao_sendmail/<int:pk>/', views.enviar_email, name='inscricao_sendmail'),
    path('inscricao_sendmassmail/<int:pk>/', views.enviar_email_coletivo, name='inscricao_sendmassmail'),
    path('inscricao_detail/<int:pk>/', views.inscricao_detail_view, name='inscricao_detail'),
    # projeto
    path('projetos_list/<int:pk>/', views.projeto_list_view, name='projetos_list'),
    path('projeto_detail_superuser/<int:pk>/', views.projeto_detail_list_view, name='projeto_detail_superuser'),
    path('bibliografia_detail_superuser/<int:pk>/', views.bibliografia_detail_superuser, name='bibliografia_detail_superuser'),
    path('introducao_detail_superuser/<int:pk>/', views.introducao_detail_superuser, name='introducao_detail_superuser'),
    path('teoria_detail_superuser/<int:pk>/', views.teoria_detail_superuser, name='teoria_detail_superuser'),
    path('metodologia_detail_superuser/<int:pk>/', views.metodologia_detail_superuser, name='metodologia_detail_superuser'),
    path('resultado_detail_superuser/<int:pk>/', views.resultado_detail_superuser, name='resultado_detail_superuser'),
    path('apresentacao_detail_superuser/<int:pk>/', views.apresentacao_detail_superuser, name='apresentacao_detail_superuser'),
    path('financeiro_detail_superuser/<int:pk>/', views.financeiro_detail_superuser, name='financeiro_detail_superuser'),
    path('proposta_detail_superuser/<int:pk>/', views.proposta_detail_superuser, name='proposta_detail_superuser'),
    path('extra_detail_superuser/<int:pk>/', views.extra_detail_superuser, name='extra_detail_superuser'),
    # inscricao-usuario
    path('inscricao_extra/<int:pk>/', views.inscricao_extra_view, name='inscricao_extra'),
    path('inscricao_proposta/<int:pk>/', views.inscricao_proposta_view, name='inscricao_proposta'),
    path('inscricao_financeiro/<int:pk>/', views.inscricao_financeiro_view, name='inscricao_financeiro'),
    path('inscricao_apresentacao/<int:pk>/', views.inscricao_apresentacao_view, name='inscricao_apresentacao'),
    path('inscricao_bibliografia/<int:pk>/', views.inscricao_bibliografia_view, name='inscricao_bibliografia'),
    path('inscricao_projeto/<int:pk>/', views.inscricao_projeto_view, name='inscricao_projeto'),
    path('inscricao_introducao/<int:pk>/', views.inscricao_introducao_view, name='inscricao_introducao'),
    path('inscricao_status/<int:pk>/', views.inscricao_update_status_view, name='inscricao_status'),
    path('ranking_list/<int:pk>/', views.ranking_list, name='ranking_list'),
    path('projetos_destaque_list/<int:pk>/', views.projetos_destaque_list_view, name='projetos_destaque_list'),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    # homepage
    path('', views.HomePageDetail, name='home'),
    # noticia
    path('noticia_detail/<int:pk>/', views.noticia_detail_view, name='noticia_detail'),
    path('noticias_list/', views.noticias_list_view, name='noticias_list'),
]

progressus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('users/', include('users.urls', namespace='users')),
    path('cadastros/', include('cadastros.urls', namespace='cadastros')),
    path('chamadas/',include('chamadas.urls', namespace='chamadas')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('profile/', views.profile_update_view, name='profile'),
    path('reset_password/', views.PasswordReset.as_view(), name="reset_password"),
    path('reset_password_sent/', views.PasswordResetDone.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(),name="password_reset_confirm"),
    path('reset_password_complete/', views.PasswordResetComplete.as_view(), name="password_reset_complete"),
    path('send_mail/<int:pk>/', views.enviar_email, name='send_mail'),
]

pages/templates/pages/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    <!-- Core theme CSS (includes Bootstrap)-->
    <!--
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.6/dist/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    <title>{% block title %}Progressus project{% endblock %}</title>

</head>
<body class="d-flex flex-column min-vh-100">

    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;" class="bi">
        <symbol id="github" viewBox="0 0 16 16">
            <title>GitHub</title>
            <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
        </symbol>
        <symbol id="house" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M2 13.5V7h1v6.5a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5V7h1v6.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5zm11-11V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
            <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
        </symbol>
        <symbol id="telefone" fill="currentColor" class="bi bi-telephone" viewBox="0 0 16 16">
            <path d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/>
        </symbol>
        <symbol id="email" fill="currentColor" class="bi bi-envelope" viewBox="0 0 16 16">
            <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z"/>
        </symbol>
      </svg>
    
    {% block menu %}
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4 mx-1">
          <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'pages:home' %}"><em>PROGRESSUS</em></a>
              <div class="collapse navbar-collapse" id="collapsenavbar">
                <div class="navbar-nav ms-auto">
                  <div class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active" id="dropdownchamada" role="button" href="#" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">Chamadas</a>
                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownchamada">
                      <a class="dropdown-item" href="{% url 'chamadas:chamadas_abertas' %}">Abertas</a>
                      <a class="dropdown-item" href="{% url 'chamadas:chamadas_andamento' %}">Em andamento</a>
                      <a class="dropdown-item" href="{% url 'chamadas:chamadas_encerradas' %}">Encerradas</a>
                    </div>
                  </div>
                {% if request.user.is_authenticated %}
                    {% if request.user.is_superuser %}
                      <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="dropdowncadastro" role="button" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true" href="#">Cadastro</a>
                          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdowncadastro">
                            <a class="dropdown-item" href="{% url 'cadastros:profiles_list' %}">Usuários</a>
                            <a class="dropdown-item" href="{% url 'cadastros:chamadas_list' %}">Chamadas</a>
                            <a class="dropdown-item" href="{% url 'cadastros:noticias_list' %}">Notícias</a>
                            <a class="dropdown-item" href="{% url 'cadastros:temas_list' %}">Temas</a>
                            <a class="dropdown-item" href="{% url 'cadastros:turmas_list' %}">Turmas</a>
                            <a class="dropdown-item" href="{% url 'cadastros:projetomodelo_list' %}">Modelo de projeto</a>
                        </div>
                      </div>
                    {% endif %}
                    <div class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" id="dropdownlogin" role="button" href="#" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">
                        {{ request.user }}
                      </a>
                      <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownlogin">
                        {% if request.user.is_superuser %}
                          <a class="dropdown-item" href="{% url 'chamadas:chamadas_list_superuser' %}">Chamadas</a>
                        {% else %}
                          <a class="dropdown-item" href="{% url 'users:profile' %}">Meus dados</a>
                          <a class="dropdown-item" href="{% url 'chamadas:inscricao_list_user' %}">Minhas inscrições</a>
                        {% endif %}
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'users:logout' %}">Sair</a>
                      </div>
                    </div>
                    {% else %}
                      <a class="nav-item nav-link active" href="{% url 'users:login' %}">Login</a>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </nav>
  {% endblock %}

    {% block header %}
      <div class="container">
      </div>
    {% endblock %}

    {% block content %}
      <div class="container" style="font-size: 11pt;">
          Em construção...
      </div>
    {% endblock %}

    {% block extra %}
    {% endblock %}

    {% block footnote %}
      <footer class="d-flex align-items-center py-1 mt-2 mb-0 bg-light text-muted" style="position: relative; height:fit-content; bottom: 0vh;">
        <div class="container-fluid" style="font-size: small;">
          <div class="row align-items-start">
            <div class="col-xl-3 mx-left mt-1">
              <h6 class="text-uppercase text-center">
                Sobre
              </h6>
              <p>
                Plataforma Progressus é um sistema on-line para submissão, acompanhamento e divulgação de projetos de iniciação científica.
              </p>
            </div>
            <div class="col-xl-3 mx-left mt-1">
              <h6 class="text-uppercase text-center">
                Links importantes
              </h6>
              <ul class="list-unstyled">
                <li><a class="link-secondary" style="text-decoration: none;" href="https://irati.ifpr.edu.br/">Site institucional do IFPR - campus Irati</a></li>
                <li><a class="link-secondary" style="text-decoration: none;" href="https://www.even3.com.br/sipex2021irati/">SIPEX VII</a></li>
                <li><a class="link-secondary" style="text-decoration: none;" href="https://irati.ifpr.edu.br/eventos/eventos-2021/iftech-2021/">IX IFTECH</a></li>
              </ul>
            </div>
            <div class="col-xl-3 mx-left mt-1">
              <h6 class="text-uppercase text-center">
                Patrocinadores
              </h6>
              Desde já agradecemos por sua doação. Logo os administradores do evento irão divulgar a lista de patrocinadores.
            </div>
            <div class="col-xl-3 mx-left mt-1">
              <h6 class="text-uppercase text-center">
                Contato
              </h6>
              <ul class="list-unstyled">
                <li"><svg width="16" height="16"><use xlink:href="#house"/>
                </svg><span class="ms-2">Rua Pedro Koppe, 100, Vila Matilde, Irati-Pr</span></li>
                <li><svg width="16" height="16"><use xlink:href="#telefone"/>
                </svg><span class="ms-2">42 2104-0200</span></li>
                <li><svg width="16" height="16"><use xlink:href="#email"/>
                </svg><span class="ms-2">flavianowilliams@gmail.com</span></li>
              </ul>
            </div>
          </div>
          <div class="border-top d-flex bd-highlight mb-0 py-2">
            <span class="bd-highlight">
              © 2022, MIT license. Developed by Flaviano Williams Fernandes
            </span>
            <span class="ms-auto bd-highlight">
              <a href="https://github.com/flavianowilliams/progressus">
                <svg width="20" height="20"><use xlink:href="#github"/>
                </svg>
              </a>
            </span>
          </div>
        </div>
      </footer>
    {% endblock %}

    <!-- Bootstrap core JS-->
    <!--<script src="{% static 'js/bootstrap.min.js' %}"></script>-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!-- Core theme JS-->
    <!--<script src="js/scripts.js"></script>-->
    <!-- extras -->
    <!--<script src="{% static 'js/popper.min.js' %}"></script>-->
    <!--<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>-->

</body>
</html>

pages/templates/pages/index.html
{% extends "pages/base.html" %}

{% load static %}

{% block title %}Progressus{% endblock %}

{% block content %}
    <div class="container-fluid">
        {% for object in chamada %}
            {% now "d-m-Y" as today %}
            {% if today == object.deadline_inscricao|date:"d-m-Y" %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>Atenção! Encerra hoje o prazo para a inscricao na chamada {{ object }}.</strong>
                    <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% elif today == object.deadline_bibliografia|date:"d-m-Y" %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>Atenção! Encerra hoje o prazo para o envio da revisão bibliográfica.</strong>
                    <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% elif today == object.deadline_proposta|date:"d-m-Y" %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>Atenção! Encerra hoje o prazo para o envio da proposta de trabalho.</strong>
                    <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% elif today == object.deadline_projeto|date:"d-m-Y" %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>Atenção! Encerra hoje o prazo para o envio do projeto de pesquisa.</strong>
                    <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}
            {% if object.aviso %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>Chamada {{ object }}: Atenção! {{ object.aviso }}</strong>
                    <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}
        {% endfor %}
        <h4>Notícias</h4>
        {% for object in noticia %}
            <div class="border-top p-3" style="text-align: center;">
                <a href="{% url 'pages:noticia_detail' object.pk %}"><img src="{{ object.noticia.imagem.url }}" alt="imagem de noticia" style="height: 50vh;"></a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

pages/templates/pages/noticia_detail.html
{% extends 'pages/base.html' %}

{% load static %}

{% block content %}
    <div class="container-fluid" style="display: flex;">
        <div class="mx-2">
            <img src="{{ object.noticia.imagem.url }}" alt="imagem de noticia" style="height: 50vh;">
        </div>
        <div class="mx-2">
            <p><strong>{{ object.noticia.titulo }}</strong></p>
            <p><em>Atualizado em {{ object.updated }}.</em></p>
            <p>{{ object.noticia.texto }}</p>
            {% if object.noticia.link %}
                <p>Acesse o <a href="{{ object.noticia.link }}">site</a> para maiores informações.</p>
            {% endif %}
        </div>
    </div>
    <br>
    <div class="container mx-4">
        <a href="{% url 'pages:noticias_list' %}">Ver notícias anteriores.</a>
    </div>
{% endblock %}

pages/templates/pages/noticias_list.html
{% extends 'pages/base.html' %}

{% load static %}

{% block content %}
    <div class="container-fluid mx-2">
        <h3>Notícias</h3>
        <hr>
        {% for object in object_list %}
            <h4><strong>{{ object.noticia.titulo }}</strong></h4>
            <p><em>Atualizado em {{ object.updated }}.</em></p>
            <p>{{ object.noticia.texto }}</p>
            <a href="{% url 'pages:noticia_detail' object.pk %}">Ver notícia</a>
        {% empty %}
            <p>Nenhuma notícia registrada.</p>
        {% endfor %}
    </div>
{% endblock %}